var asideData = {
	download: {
		title: "Download",
		file: " tar.gz file "
	},
	maintained:  " is maintained by ",
	generated: "This page was generated by ",
	theme: "using the Architect theme by ",
	design: "Design modifications made ​​by ",
	and: " and ",
	urlFacebook: "https://www.facebook.com/pages/Xfce-installer-script-for-Ubuntu/560772053963955"
}
	
var asideTemplate = Handlebars.templates['aside.template']; 
document.getElementById('aside-template').innerHTML = asideTemplate(asideData);
